server:
  port: ${PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://dpg-d8pg1p9194ac739ae2t0-a/bancopaquera
    username: bancopaquera_user
    password: Ihi08bQ45RjmNNOQMhKXwt744Lvzh8Y0
    driver-class-name: org.postgresql.Driver
 
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
